### ISSUE TITLE
change adapters conditionally

### ISSUE THREAD

**Issue by dbwieland18** [rails-api/active_model_serializers#1042]
I'm wanting to implement the jsonapi adapter for version 2 of an api, but I understand that this configuration is set in an initializer, according to the docs. Any ideas for specifying a different adapter ONLY for requests to V2 routes?

**Comment by dbwieland18** [comment]
just came across another issue mentioning that the default adapter can be overridden for certain actions like this
```
render json: movie, adapter: :json_api
```
maybe that's my answer?

**Comment by bolshakov** [comment]
AMS does not support this feature by itself not, but this behavior easy to achieve.

```ruby 
class ApplicationController < ActionController::Base
  # @see for inspiration  https://github.com/rails-api/active_model_serializers/blob/master/lib/action_controller/serialization.rb#L48
  [:_render_option_json, :_render_with_renderer_json].each do |renderer_method|
    define_method renderer_method do |resource, options|
      super(resource, options.merge(adapter: adapter))
    end
  end

  class_attribute :adapter
end

class V1Controller < ApplicationController
  adapter :flatten_json
end

class V2Controller < ApplicationController
  adapter :json_api
end
```

**Comment by bolshakov** [comment]
I found ancient age [discussion about using Responders](https://github.com/rails-api/active_model_serializers/pull/228) instead of overriding internal methods `_render_option_json` and `_render_with_renderer_json`.

I think using responders may solve the same problem more elegant way. In my code base I have several overriding of those methods. For example:

Fields for serialization:
```ruby
module SerializerFields
  def _render_option_json(resource, options)
    super(resource, options.merge(serializer_fields))
  end

  def _render_with_renderer_json(resource, options)
    super(resource, options.merge(serializer_fields))
  end

  private

  def serializer_fields
    { fields: params[:fields] }.compact
  end
end
```

Includes for serialization
```ruby
module SerializerIncludes
  def _render_option_json(resource, options)
    super(resource, options.merge(serializer_includes))
  end

  def _render_with_renderer_json(resource, options)
    super(resource, options.merge(serializer_includes))
  end

  private

  def serializer_includes
    { include: params[:include] }.compact
  end
end
```

Meta
```ruby
module SerializerMeta
  def _render_option_json(resource, options)
    super(resource, options.deep_merge(meta: meta))
  end

  def _render_with_renderer_json(resource, options)
    super(resource, options.deep_merge(meta: meta))
  end

  private

  def meta
    {
      status: response.status
    }
  end
end
```

Pagination
```ruby 
module SerializerPagination
  def _render_option_json(resource, options)
    if paginated?(resource)
      super(resource, options.deep_merge(meta: { pagination: resource.pagination }))
    else
      super
    end
  end

  def _render_with_renderer_json(resource, options)
    if paginated?(resource)
      super(resource, options.deep_merge(meta: { pagination: resource.pagination }))
    else
      super
    end
  end

  private

  def paginated?(resource)
    resource.respond_to?(:pagination)
  end
end
```

I also thinking about conditional rendering created resource based on [Prefer Header](http://tools.ietf.org/html/rfc7240).

It looks like responders perfect choice for that needs (Actually I have never used them)
@joaomdmoura what do you think?

**Comment by joaomdmoura** [comment]
@dbwieland18  as @bolshakov mentioned right now we do not support it with an application-wide feature but you could use an adapter string instead of an option to override it on a specific render.

Indeed @bolshakov I already had to implement a similar thing that would change the adapter accordingly the MIME Type. (for json-api).

I'm not in favor or using `respond_with` instead of the render methods, it might be confusing. People are used to `render`, and Rails is already supporting us this way.

But I'm favor of easily enable ppl to use multiple adapters at the same time, despite of not being a usual case to new apps, it might help ppl trying to gracefully upgrade to new conventions as `json-api`.

About the overriding methods I think we can discuss solution on another issue maybe, because it's an interest matter by itself. :smile: 

@dbwieland18 let me know if the `render` solution worked or which solution you used  and if there is something else we can help u with.

**Comment by dbwieland18** [comment]
Thanks for the thoughts! I've ended up just using an adapter string for testing the json-api adapter for my V2, but I'll keep the other techniques in mind once we settle on something.
