### ISSUE TITLE
Creating adapters by media-types.

### ISSUE THREAD

**Issue by bacarini** [rails-api/active_model_serializers#1062]
I would like to know what is yours thoughts about creating adapters by `media-types`.
Ex.
```
GET http://example.com/posts  
render with flatten-json adapter

GET http://example.com/posts  --headers "Content-type: application/vnd.api+json" 
render with json-api adapter

GET http://example.com/posts  --headers "Content-type: application/json" 
render with json adapter

GET http://example.com/posts  --headers "Content-type: application/hal+json" 
render with hal adapter (hypothetically)

GET http://example.com/posts  --headers "Content-type: application/vnd.collection+json" 
render with collection-json adapter (hypothetically)
```
@akakuruma and I want to implement that if it is approved.

**Comment by joaomdmoura** [comment]
I've implemented it on a fork of AMS already, with some hacks.
I'm not sure about it yet, for json-api it makes a lot of sense, but it seems the kind of decision you don't want to infer, once you even have the initializer to set it, or the possibility to lock it on one adapter using the `adapte` options on `render`.
Also not sure if it could bother something to ppl that use ActionController::Responder.

I'll keep this open for now, but we might need some ppl backing this up in order to make it happen :smile:

**Comment by akaKuruma** [comment]
@joaomdmoura could you share your implementation?

**Comment by joaomdmoura** [comment]
https://github.com/ride/active_model_serializers/blob/support-rc1-and-1-0-jsonapi/lib/action_controller/serialization.rb#L29

**Comment by bacarini** [comment]
@joaomdmoura, we were thinking about it but not has default. As long as user send it through `render` We will not override it.
ex.
If adapter options is defined on `render`, AMS will serialize the model even if the user sends headers with `application/hal+json`(hypothetically). But if it is not specify on `render` we may look at `content-type`.
At last, if there is netheir defined in `render` nor `content-type`, it could get from initializer configuration.

Does it make sense? Did I make myself clear? :smile: 

What do you think?

**Comment by beauby** [comment]
I'm interested to know about the use cases of this feature.
