### ISSUE TITLE
Config option to enforce an ActiveModel::Serializer for every model

### ISSUE THREAD

**Issue by lukehorvat** [rails-api/active_model_serializers#1068]
It would be nice if one could ensure that every model is serialized by an `ActiveModel::Serializer`, and if one doesn't exist for a given model, raise an error (instead of silently using the model's default serialisation). I'm thinking a config option like `ActiveModel::Serializer.config.required = true` (defaulting to `false`).

I don't have any familiarity with the codebase, but if I'm not mistaken, it would simply be another `else if` [here](https://github.com/rails-api/active_model_serializers/blob/master/lib/action_controller/serialization.rb#L37).

**Comment by joaomdmoura** [comment]
Hey @lukehorvat, thank you for this issue, this is not something I would personally use right now, seems and edge case to me, but I wold not discard it if a PR comes along. 

On the other hand, when using json-api as @beauby mentioned on #1075 it seems something that we should have, maybe we could try to solve both using the same implementation underneath the code, so `ActiveModel::Serializer.config.required` would be set to `true`` automatically when using json-api or something like that.

But I'd go with a `warning` instead of raise an error.

**Comment by sandstrom** [comment]
@lukehorvat Could probably be implemented with a module included in your models, e.g. `module Ensure; def as_json; raise NotImplementedError, 'Must use serializer'; end; end;`

I don't want to sound negative, but in my view this isn't very useful to have built-in, since it's pretty easy to roll your own.

**Comment by joaomdmoura** [comment]
Indeed @sandstrom. I would still review a PR with this if someone is interested but I'd recommend to go with the solution above.

**Comment by cantino** [comment]
I think the default behavior of AMS should be to error if a serializer cannot be found.  Otherwise, it's easy to stumble into a major security hole.

Imagine you have a controller, maybe something like:

```ruby
class RecentUsersController < ApplicationController
  def index
    render json: User.recent.limit(5)
  end
end
```

and a serializer:

```ruby
class UserSerializer < ActiveModel::Serializer
  attribute :first_name
  attribute :user_since
end
```

Now, imagine you either put that serializer at the wrong path by accident, or you named it `RecentUserSerializer`, but forgot to specify it by name in the render call.  Either way, you're now calling `as_json` on the models and handing hashed passwords out over your API.


I'm using something like this to fix the issue, but I think it should be default behavior:

```ruby
module ErrorOnMissingSerializer
  module AsJSONOverride
    def as_json(*_)
      serializable_resource = ActiveModelSerializers::SerializableResource.new(self)
      if serializable_resource.serializer
        serializable_resource.as_json
      else
        raise NotImplementedError, "No serializer was found for #{self.class.name}"
      end
    end
  end

  class Railtie < Rails::Railtie
    ActiveSupport.on_load :active_record do
      ActiveRecord::Base.include ErrorOnMissingSerializer::AsJSONOverride
    end
  end
end
```

**Comment by bf4** [comment]
@cantino can you create a new issue to discuss this?

**Comment by cantino** [comment]
Sure! #1853
