### ISSUE TITLE
Non-compliant JSONAPI tests

### ISSUE THREAD

**Issue by beauby** [rails-api/active_model_serializers#1112]
While investigating the relevance of virtual values for relationships with the `json_api` adapter, I came across those tests, which expect an output that is not JSONAPI compliant:
+ [test_has_many_with_no_serializer](https://github.com/rails-api/active_model_serializers/blob/master/test/adapter/json_api/has_many_test.rb#L111)
  + expected output: `{:data=>{:id=>"1", :type=>"posts", :relationships=>{:tags=>{:data=>[{"attributes"=>{"id"=>1, "name"=>"#hash_tag"}}]}}}}`
+ [test_has_many_with_virtual_value](https://github.com/rails-api/active_model_serializers/blob/master/test/adapter/json_api/has_many_test.rb#L126)
  + expected output: `{:data=>{:id=>"1", :type=>"virtual_values", :relationships=>{:maker=>{:data=>{:id=>1}}, :reviews=>{:data=>[{:id=>1}, {:id=>2}]}}}}`
+ [test_has_one_with_virtual_value](https://github.com/rails-api/active_model_serializers/blob/master/test/adapter/json_api/has_one_test.rb#L60)
  + expected output: `{:data=>{:id=>"1", :type=>"virtual_values", :relationships=>{:maker=>{:data=>{:id=>1}}, :reviews=>{:data=>[{:id=>1}, {:id=>2}]}}}}`

**Comment by joaomdmoura** [comment]
I know this sound tricky, and we really love and want to help ppl to use json-api, but I'd keep virtual value for now, mostly because is something some ppl are kind used to, and it does not impact others that want to follow the convention.
The `no_serializer` could be overridden to follow the conventions though
