### ISSUE TITLE
Using 0.9.x and 0.10.x in same project

### ISSUE THREAD

**Issue by yoda** [rails-api/active_model_serializers#1136]
Hi All,

I am working on a largish rails codebase which uses 0.9.x for all the json serialisation. I want to start using the jsonapi style adapter either along side or as a engine or something so that I do not have to change all the 0.9.x code directly to 0.10.x. However I am at a loss as to how to get them to play nice together. As I have heaps of legacy stuff dependent on 0.9.x and want to slowly move stuff over to 0.10.x is there any way to be able to do this without having to do it all at once. 

I saw a question/issue similar to this a while ago however I have not been able to find it again.

Also, thank you all for your great work.

**Comment by beauby** [comment]
Good question. If somebody comes up with a satisfying answer to this one, I think it is worth putting in the docs.

**Comment by NullVoxPopuli** [comment]
I don't know if this is possible due to how bundler works. (unless there is something I don't know about -- which is likely)

What functionality are you wanting that is different between the two versions?

With 0.10 RC3 and forward, you'll be able to specify adapters manually in your controllers - so that would help with the json api using

**Comment by yoda** [comment]
Well our current "api" is a mess and using 0.9.x (it works but its not standardised etc). In 0.9.x we are using the default serialisation mode that it supports (with heavily customised serialisers). Whereas with the 0.10.x I wanted to use  the json_api mode one. So ideally it would be that I could somehow use the 0.9.x style for some and then the json_api style for others. If I need to do this as a case by case basis it would be best if it was in the way that the old code could stay untouched and I could add the json_api stuff specifically as I add / convert new stuff. Obviously this is the nice case but if its not possible than I guess the opposite would be ok too (specifying on old, defaulting on new).

**Comment by joaomdmoura** [comment]
@NullVoxPopuli On RC2 you can already specify adapter manually in controller I think.
@yoda  I've done something similar in order to keep different versions of JSON-API on the same application. There are a lot of way of making this work but two specially that looks nicer.

- If there are no specific 0.9 features involved basically you would want to use multiple adapter, and in order to do this you can use the `accept` HTTP header with the specified `media type` on [JSON API](http://jsonapi.org/format/#introduction). You can do it by youself but there is also a [PR opened](https://github.com/rails-api/active_model_serializers/pull/1082) that would implement this on the AMS

- If it something more dependent on something of 0.9, some specific serialization format for example, then the easiest way would be to write an adapter that would implement this specific behavior.

But right now you could use the first option already on RC2 :grin:

**Comment by yoda** [comment]
Ah ok I'll give those a go. Thanks.

**Comment by yoda** [comment]
#1005
