### ISSUE TITLE
Improve the command line message  [Ynaqdh]

### ISSUE THREAD

**Issue by julianosaless** [rails-api/active_model_serializers#1207]
Hello everyone, sorry for my English :)

I am new user the api active_model_serializer, when i was using i think confused this command in label red  below:

**Before** :
![help](https://cloud.githubusercontent.com/assets/1616798/10126616/309e0f50-656c-11e5-96ba-eecf5ccc410b.JPG)

The **[Ynaqdh]**  is confused because one is word, because it does not seem  one list the individual command.

**After**
Overwrite /home/ubuntu/workspace/app/models/post.rb? (enter "h" for help) [`y | n | a | q | d | h`] 

What do you think ?

**Comment by beauby** [comment]
Hi @julianosaless, thanks for taking the time to report this issue. However, this behavior is part of rails, not of active_model_serializers (we have no control over the way rails handles file conflicts during generation of files), so you should bring this up to the rails team.

Closing this, since it is not AMS-related.

**Comment by julianosaless** [comment]
Thank You @beauby , i will send pr to show this information at documentation AMS
