### ISSUE TITLE
put back 0.9.x serializer instance #to_hash or #serializable_hash

### ISSUE THREAD

**Issue by maliqq** [rails-api/active_model_serializers#1321]
instead of

```ruby
ActiveModel::SerializableResource.new(@message, serializer: MySerializer)
```

to this
```ruby
MySerializer.new(@message).to_hash # or #serializable_hash
```

**Comment by bf4** [comment]
Would you mind clarifying which ams version you're targeting? Also, what's your use case? Call serializer.attributes if you want the raw attributes.

**Comment by nikolai-b** [comment]
This is an issue on master.  I'm using rocket pants which [uses that method](https://github.com/Sutto/rocket_pants/pull/138/files).  It isn't a big issue to change but `MySerializer.new(@message).serializable_hash` does feel a bit nicer to use.

**Comment by bf4** [comment]
This issue comes up a lot in the 0.10 series.  Someone (me? you?)  should really add this to [common issues and resolutions section in contributing](https://github.com/rails-api/active_model_serializers/blob/master/CONTRIBUTING.md#common-issues-and-resolutions)

So, tl;dr the serializer has a different interface because it is different.  I'm not sure what kind of output you're expecting, but you could monkey patch the serializer with a call to the serializable resource and the attributes adapter.

The serializer in the 0.10 series does have an `attributes` and `associations` method, but I'm not sure that's what you want.

I'll add a comment in that PR. Thanks for the link.

**Comment by bf4** [comment]
I'm going to close this, but feel free to continue asking questions, and re-open if you think there's a solution that fits in this lib.

**Comment by bf4** [comment]
btw, this is now done in 0.10.0 :)
