### ISSUE TITLE
Meta key not being picked up !!

### ISSUE THREAD

**Issue by NeoElit** [rails-api/active_model_serializers#1328]
Custom meta not showing up even with root on active_model_serializers (0.9.3).
```
render :json => @place, :serializer => PlaceSerializer, :meta => {:content => "10", :type => "success"}
```
is working fine and meta is retrieved, however with:
```
render :json => @place, :serializer => PlaceSerializer, :meta => {:content => "10", :type => "success"}, :meta_key => 'message'
```
it's not giving any meta or message.

**Comment by NeoElit** [comment]
tried same with version 0.8.3 and worked fine.
Seems like an issue with 0.9.3

**Comment by LoganD** [comment]
I'm using 0.9.3 with the following code and it works:
```      render json: data,
             root: 'results',
             serializer: serializer,
             meta: meta(request, @query, error),
             status: code```

My meta function returns an object, so trying making the object before you render.

**Comment by bf4** [comment]
@NeoElit thanks for the issue. Have you taken a look at the code to see what might be happening?

**Comment by NeoElit** [comment]
@bf4 following is the render code and response in test
```
$ render code:
render json: @place,
                 serializer: PlaceSerializer,
                 meta: {code: 200, message: "successful"},
                 meta_key: "status" and return

$ response: 
{"place"=>{"id"=>903798785, "title"=>"new toit"}}
```

**Comment by NeoElit** [comment]
@LoganD 
How did meta({hash}) works for you? It's throwing no method error for me.
Following is the render code and reponse
```
$ render code:
render json: @place,
                 serializer: PlaceSerializer,
                 meta: meta({code: 200, message: "successful"}), status: 200 and return

$ response:
NoMethodError:         NoMethodError: undefined method `meta' for #<Client::Api::V1::PlacesController:0xac5b764>
```

**Comment by LoganD** [comment]
@NeoElit Sorry for the confusion, meta was a function that I wrote.
```
def make_meta(message, code)
{
  code: code,
  message: message
}
end
```

then in the render `meta: make_meta(code, message)`.
Since you can return a status code as a separate param, you don't need to return that in the meta, unless that has a different meaning and is specific to your api. I made that function so that I can do customized formatting for the meta block since that render function is generic.

**Comment by NeoElit** [comment]
@LoganD it doesn't solve the problem rt?  This method just returns the hash to render. However what i need is to change root/name of meta.

**Comment by LoganD** [comment]
Ah, I see that now @NeoElit. Is there a reason you don't want to use meta for the details and status just for the http status code? 
I have a work around for this, but it involved making the whole return object separately, not in the render statement. 

First I serialize the data by doing either:
`serialized_data = ActiveModel::ArraySerializer.new(data, each_serializer: serializer_name, root: false)`
or 
`serialized_data = serializer_name.new(data, root: false)`

And then I construct the response object:
```
response = {
      results: data,
      details: details,
      meta_key_or_whatever_you_want_to_call_it: meta(request, query, error)
    }
```
and then I send it back:
`render json: response, status: code`

**Comment by NeoElit** [comment]
@LoganD  Thank you.
-----------
Is there a reason you don't want to use meta for the details and status just for the http status code? 
-----------
Actually No. Api was designed liked that. That's it. :)

However isn't it a bug? Because documentation says you can customize meta then and there,

**Comment by LoganD** [comment]
I needed to do that because I wanted to add another main key and couldn't do that in the render function anyway. I just looked at the docs for that and I think I found your issue (from the docs):
`render json: @posts, serializer: CustomArraySerializer, meta_object: {total: 10}, meta_key: 'meta_object'`
The key name used needs to be the key name specified by the `meta_key` param:
```
render json: @place,
             serializer: PlaceSerializer,
             message: { content: "10", type: "success" },
             meta_key: 'message'
```
I didn't have time to test it out but hopefully that solves your problem.

**Comment by NeoElit** [comment]
@LoganD  I don't think it's syntax issue since it works with other versions unless there is a change.

**Comment by foucist** [comment]
Was this fixed?

I have this exact issue on active_model_serializers v0.9.4,

meta & meta_key was working fine in v0.8.3

**Comment by vinodlala** [comment]
For `meta_key`, use a symbol instead of a string.

The docs on http://www.rubydoc.info/gems/active_model_serializers/0.9.5 has this:

```
render json: @posts, serializer: CustomArraySerializer, meta_object: {total: 10}, meta_key: 'meta_object'
```

But that doesn't work.

This will work:

```
render json: @posts, serializer: CustomArraySerializer, meta_object: {total: 10}, meta_key: :meta_object
```

In `lib/active_model/serializer.rb`, check out the `initialize` method:

```
      @meta_key      = options[:meta_key] || :meta
      @meta          = options[@meta_key]
```

If `options[:meta_key]` is `nil`, `@meta_key` is `:meta` (a symbol, not a string).

Using the example in the docs, if `options[:meta_key]` is a string like `'meta_object'`, `@meta_key` is `'meta_object'` (a string, not a symbol).  

However, `options['meta_object']` does not exist. Only `options[:meta_object]` exists.

If `options[:meta_key]` is a symbol like `:meta_object`, `@meta_key` is `:meta_object`, which works.

**Comment by shhavel** [comment]
What if needed to provide a case for two meta objects (and keys)?
It sounds strange but still maybe needed to support some format that cannot be changed by requirements.
Maybe interface similar to this one: 

```ruby
render json: @place, serializer: PlaceSerializer, adapter: :json, root: :data,
  merge_with: { meta: { content: "10", type: "success" }, message: "Successfully updated" },
```

that will result in:

```json
{ 
  "data": {
    "id": 1,
    "name": "Some Place"
  },
  "meta": {
    "content": "10",
    "type": "success"
  },
  "message": "Successfully updated"
}
```

**Comment by bf4** [comment]
@shhavel I have no idea what version of the gem you're using or why you aren't specifying :meta_key. Please open a new issue and fill out the requested questions.
