### ISSUE TITLE
Serializer manually

### ISSUE THREAD

**Issue by fabiancarlos** [rails-api/active_model_serializers#1382]
I can be wrong, but can i call the oject model serializer to create on manually? Like this.

UserSerializer.new(@user)

**Comment by remear** [comment]
Assuming you're using 0.10.x, is this what you're looking to do? https://github.com/rails-api/active_model_serializers/blob/master/docs/howto/outside_controller_use.md

**Comment by bf4** [comment]
Thanks @remear 

Closing due to too little information.  Please see https://github.com/rails-api/active_model_serializers/blob/master/CONTRIBUTING.md for what we need, then re-open and let's continue the discussion. (This just keeps issues from staying open if the poster never comes back :)

@rails-api/ams we have in the docs to use stackoverflow for questions.  Should we keep that, change it to slack, or no-op?
