### ISSUE TITLE
JSON document is not compatible with json schema

### ISSUE THREAD

**Issue by cmrd-senya** [rails-api/active_model_serializers#1556]
#### Expected behavior vs actual behavior

I have a model with optional string fields. When a field is not set it is serialized as null and if it is set it is serialized as string. However if I try to validate this field against [JSON schema](http://json-schema.org/latest/json-schema-core.html#anchor8) string type, the validation fails when it equals to null.

I want my serialized document to be exportable in a compatible way with JSON schema so I can validate it against a schema. So I expect optional fields to be serialized as empty strings rather than null value.

#### Steps to reproduce
*(e.g., detailed walkthrough, runnable script, example application)*

- Define model schema with optional fields (https://github.com/diaspora/diaspora/blob/develop/db/schema.rb#L475)
- Define a serializer for that object (https://github.com/diaspora/diaspora/blob/develop/app/serializers/export/profile_serializer.rb)
- Make a jsone schema for that object (https://github.com/cmrd-senya/diaspora/blob/archive-schema/app/schemas/archive-format.json#L34). Optional fields like "first_name" is of type string
- Export an object with optional fiels unset
- In the [exported document](https://gist.githubusercontent.com/cmrd-senya/83fbf34f4ef34570a6c5/raw/72a5f16710229377b90ba70ce67919b70b748a0a/export.json) find the optional field (first_name) equal to null rather than to empty string

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: 0.9.4

Output of `ruby -e "puts RUBY_DESCRIPTION"`: ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]

OS Type & Version: Debian 8

Integrated application and version *(e.g., Rails, Grape, etc)*: Rails 4.2.5.1

**Comment by groyoh** [comment]
Hi @cmrd-senya. I'm not sure I understood the real issue here. Do you want `null` values to always be serialized as `""` (empty strings)?

Wouldt it be possible for you to change the JSON schema to accept `null` values instead?

```json
"first_name": {
  "id": "https://the-federation.info/specs/backup-restore#archive_format/user/profile/first_name",
  "type": ["string","null"]
}
```

**Comment by cmrd-senya** [comment]
Yes, I thought that a value maybe serialized as a single string type, and if case it's null it is serialized as "".

I didn't know of possibility of picking two types at the same moment (read the documentation inattentive, my fault), that probably would fit me.

**Comment by groyoh** [comment]
@cmrd-senya I guess that's up to you to define the behavior. Using `""` would be a valid use case for certain people, other prefer to not serialize it at all to minimize response size (which could be your case since [profile](https://github.com/cmrd-senya/diaspora/blob/archive-schema/app/schemas/archive-format.json#L30) does not define any `required` property).

If changing the schema to allow `null` values is a valid option for you, then it's great! I'm closing this issue then. Please reopen if needed :wink:

**Comment by cmrd-senya** [comment]
Thanks!

**Comment by bf4** [comment]
@cmrd-senya I really like validating docs against a schema.  I hope to add a schema for our JSON adapter output at some point.  

As to your question, since `null` is a valid javascript value that is distinct from `""`, it would be incorrect to always render `nil` as `""`, unless there were a business rule for that.  In some cases, we leave out the key altogether when the value is `nil`.

Anything that you would like to share in the docs or code here for validating the JSON document against a schema would be much appreciated.

**Comment by bf4** [comment]
Given

```ruby
module Export
  class ProfileSerializer < ActiveModel::Serializer
end
```


```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://the-federation.info/specs/backup-restore#archive_format",
  "type": "object",
  "properties": {
  "profile": {
          "id": "https://the-federation.info/specs/backup-restore#archive_format/user/profile",
          "type": "object",
          "properties": {
            "first_name": {
              "id": "https://the-federation.info/specs/backup-restore#archive_format/user/profile/first_name",
              "type": "string"
            }
}}
}
```

As to using `gem "active_model_serializers", "0.9.4"`, we're eventually going to have an adapter for that in 0.10 so everyone can always use the latest code.
