### ISSUE TITLE
jsonapi_parse should translate key format back again

### ISSUE THREAD

**Issue by maletor** [rails-api/active_model_serializers#1612]
Key formats, introduced in #1248, should play into deserializing params as well.

Typically an application will store keys in underscore format. AMS should then convert them to dashed for JSON API. But, upon jsonapi_parse, they should be converted back to underscores. Currently, they are passed as dashed.

**Comment by pelted** [comment]
I take it this was new in RC4? My JSON API just broke all over the place with a change in key format from underscores. Not seeing a way to configure key format in the docs and these params passed back are also not deserializing.

**Comment by maletor** [comment]
Key formats are new from RC4 on master. The key format defaults are desired and correctly implemented. The reverse part, the deserialization, which is in experimental stage, is not yet implemented correctly. The deserializer should know what the attributes have been transformed to since it knows where they came from.

**Comment by maletor** [comment]
I'm interested to know how this would work with the given `only` and `except` keys. I imagine they would work as they do today and would use underscored names if we're going with the general use case.

**Comment by rthbound** [comment]
@pelted here's [the docs](https://github.com/remear/active_model_serializers/blob/c533d1a7fe202a904af178cd22c54cc14383bab0/docs/general/key_transform.md) on how to configure key format. I use `:unaltered` because my javascript clients are satisfied with underscored keys. We can't use the default (`:dashed`) yet because of the issue @snwfog just referenced ^.

I've closed that issue because I think its resolution will be required in order to close this issue.
