### ISSUE TITLE
Namespace ignored if the constant name already exists

### ISSUE THREAD

**Issue by patleb** [rails-api/active_model_serializers#1652]
I came across a scenario where I needed a namespaced serializer which has the same name as another one in the global scope, ie: `GroupSerializer` vs `Schedule::GroupSerializer`. It turns out that `Object.send method, const` [here](https://github.com/rails-api/active_model_serializers/blob/0-9-stable/lib/active_model/serializable/utils.rb#L9) returns the unscoped serializer object which has the same name.

Actually, I'm wondering why `const.safe_constantize` isn't called for all scenarios like this cc0db97f708bd9355c982e2cc670764e86b56e0f?

**Comment by bf4** [comment]
Hi @pat

Closing due to insufficient information to easily help.

Please review the requested information in our [issue template](https://github.com/rails-api/active_model_serializers/blob/master/.github/ISSUE_TEMPLATE.md) and reopen with the additional information, or any questions and comments you may have.

Thanks for your help, and thanks for making this issue.
