### ISSUE TITLE
api is ignoring "only" configuration

### ISSUE THREAD

**Issue by luizkowalski** [rails-api/active_model_serializers#1807]
I have a serializer like this

```ruby
class UserSerializer < ActiveModel::Serializer
  attributes :access_token, :first_name, :last_name
end
```

in one specific controller, I don't want to return first name and last name, so I've done this

```ruby
class V1::Auth::AnonymousController < ApplicationController
  def create
    render json: User.create(activation_state: 'anonymous'), only: :access_token, status: 201
  end
end
```

in previous version (0.9.5) it was working, but when I updated to 0.10.0, it returns the first_name and last_name as empty values on the JSON

I'm using Ruby 2.3.1p112 with Rails 4.2.6

**Comment by groyoh** [comment]
You need to use the `fields` option instead of `only` e.g. `render json: user, fields: [:access_token], status: 201`. Seems like the [docs](https://github.com/rails-api/active_model_serializers/blob/b73b780b7961b7708a40aefd016bb543a4e8137c/docs/general/rendering.md) are missing for this options, maybe you would be willing to create a PR for it?
