### ISSUE TITLE
Cache not working with collections

### ISSUE THREAD

**Issue by lmorais** [rails-api/active_model_serializers#1810]
AMS 0.10 is not caching collections, only single resources. For example, on index action the cache doesn't works, but on show action, it works perfectly.

**Comment by remear** [comment]
When someone opens an issue, we [ask for specific information](https://github.com/rails-api/active_model_serializers/blob/master/.github/ISSUE_TEMPLATE.md). Unfortunately, since this issue provides nearly none of that information, others' ability to aid in reaching a resolution to this issue is severely limited. If you'd like to pursue help with this or other issues, please provide the information we ask for in the issue template and be as detailed as possible.
