### ISSUE TITLE
Question: Override serializer_for for collection?

### ISSUE THREAD

**Issue by Rio517** [rails-api/active_model_serializers#1934]
How can I override the `serializer_for` a collection?  I would have thought ActiveModel::Serializer::CollectionSerializer.new would have been the way to go, but I noticed that the reflection is looking to instantiate a new serializer from response from serializer_for at `/lib/active_model/serializer/reflection.rb:117`

Thanks!

```ruby
class Api::V1::EventSerializer < Api::V1::BaseSerializer
  belongs_to :bookable, polymorphic: true
  has_many :users  #has_many through

  attributes :service_type, :start, :end, :service_notes

  SERIALIZER_LOOKUP = {
    'CheckinService' => Api::V1::CheckinServiceSerializer,
    'HousekeepingService' => Api::V1::HousekeepingServiceSerializer,
    'User' => Api::V1::UserSerializer
  }

  def self.serializer_for(resource, options)
    if resource.is_a?(ActiveRecord::Associations::CollectionProxy)
      #return SERIALIZER_LOOKUP[resource.first.class.name]
      return ActiveModel::Serializer::CollectionSerializer.new(resource.to_a, serializer: SERIALIZER_LOOKUP[resource.first.class.name])
    else
      return SERIALIZER_LOOKUP[resource.class.name]
    end
    super
  end

end
```

**Comment by richmolj** [comment]
@Rio517 I'm afraid I don't totally get what the issue is. Could you elaborate a bit on what you are trying to do? `serializer_for` returns the klass, `reflection.rb` instantiates an instance of that class.

It looks like the issue is for polymorphic relationships you want to specify a different serializer for each `bookable`? I don't have this use case myself but I can think of two alternatives on the top of my head:

```ruby
class HousekeepingService
  def serializer_class
    Api::V1::HousekeepingServiceSerializer
  end
end

# or

def self.serializer_for(resource, options = {})
  klass = resource.class
  if klass == ActiveRecord::Associations::CollectionProxy
    klass = resource.to_a[0].class
  end
  options.merge!(serializer: LOOKUP[klass.name]) if LOOKUP.has_key?(klass.name)
  super(resource, options)
end
```

Would either of those work for you? There might be a more eloquent solution if I better understood what you're going for.

/cc @NullVoxPopuli who is doing some work on the serializer lookup chain [here](https://github.com/rails-api/active_model_serializers/pull/1757). I think this might be relevant to your namespace-inferred-from controller stuff. I'd also note: it'd be nice if `options[:serializer]` accepted a proc for something like this.

**Comment by NullVoxPopuli** [comment]
@richmolj re that PR, I think the only thing left to do on that is to just add more tests which demonstrate what can be done with customizing the lookup chain.

**Comment by Rio517** [comment]
That's perfect, thanks @richmolj .  I didn't see I could set `def serializer_class`.  Thanks!  I also updated my question to be a little more clear in case someone else stumbles across this issue.
