### ISSUE TITLE
Calling serializers manually is not applying `key_transform`

### ISSUE THREAD

**Issue by DEfusion** [rails-api/active_model_serializers#1944]
I have the config setup with `ActiveModelSerializers.config.key_transform = :camel_lower`

If I do the serialization manually via  `SerializableResource` it works as expected:

```
ActiveModelSerializers::SerializableResource.new(e).as_json
=> {:foo=>{:id=>"330", :isFetching=>false}}
```

However if I do either of the following it does not apply the key transform:

```
s = ActiveModel::Serializer.serializer_for(e)
s.new(e).as_json
=>  {:id=>"330", :is_fetching=>false}
```

```
FooSerializer.new(e).as_json
=>  {:id=>"330", :is_fetching=>false}
```

I need to do this as I have a 2 serializers for the same model, one that excludes some attributes and another that has them all.
#### Environment

ActiveModelSerializers Version 0.10.2

**Comment by groyoh** [comment]
@DEfusion AFAIK this is not a bug per se as the serializer bypass the key transform. Fortunately when using `SerializableResource`, you can specify which serializer you would like to use. For example, `SerializableResource.new(foo, serializer: FooBarSerializer)` will use the `FooBarSerializer` instead of `FooSerializer`. I would recommend you to always use the `SerializableResource` interface instead of calling the serializer directly.

You can have a look at [this gist](https://gist.github.com/groyoh/5d7f5dc71f4463139bc395731977a370) if you want an example on how to use two serializers with the same model.

**Comment by DEfusion** [comment]
Thanks a lot for that, that works perfectly. I wonder if adding that to the [documentation on rendering outside of controllers ]( https://github.com/rails-api/active_model_serializers/blob/master/docs/howto/outside_controller_use.md#using-activemodelserializers-outside-of-a-controller) would be helpful.

**Comment by bf4** [comment]
@DEfusion This definitely needs to be documented in general as a caveat for `What happens when I call as_json/to_json on my serializer?` that none of the adapter options are applied, that only a simple mapping of the attributes and associations happens. e.g. also https://github.com/rails-api/active_model_serializers/issues/1965#issuecomment-257949274

I've love to help you with a PR
