### ISSUE TITLE
Exception when attribute is `Infinity`

### ISSUE THREAD

**Issue by ocha** [rails-api/active_model_serializers#1946]
#### Expected behavior vs actual behavior

Expected: calling `#to_json` on a serializer instance with an attribute that has value of `Infinity` should return that attribute as `null`

Actual: getting `JSON::GeneratorError: 836: Infinity not allowed in JSON` exception
#### Steps to reproduce

```
class FailCase
  include ActiveModel::Serialization

  def fail; 1/0.0; end
end

class FailCaseSerializer < ActiveModel::Serializer
  attribute :fail
end

FailCaseSerializer.new(FailCase.new).to_json
```
#### Environment

ActiveModelSerializers Version _(commit ref if not on tag)_: 0.10.2

ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]

OS Type & Version: OSX 10.11.1

Integrated application and version _(e.g., Rails, Grape, etc)_: Rails 5.0.0.1
#### Backtrace

```
Exception: JSON::GeneratorError: 836: Infinity not allowed in JSON
--
 0: /Users/afsoon/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/json/common.rb:224:in `generate'
 1: /Users/afsoon/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/json/common.rb:224:in `generate'
 2: /Users/afsoon/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/json/encoding.rb:99:in `stringify'
 3: /Users/afsoon/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/json/encoding.rb:33:in `encode'
 4: /Users/afsoon/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/json/encoding.rb:20:in `encode'
 5: /Users/afsoon/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/core_ext/object/json.rb:37:in `to_json'
```
#### Additonal helpful information

When calling `to_json` on a hash that has a key with a value of `Infinity`, rails returns `null` for that key, however with `ActiveModel::Serializer` raises an exception. Difference is that `to_json` method on `ActiveModel::Serializer` returns `Hash` instead of `Hash#to_json`:

```
serializer = FailCaseSerializer.new(FailCase.new)
serializer.to_hash #=> {:fail=>Infinity}
serializer.to_hash.to_json #=> {"fail":null}
serializer.to_json #=> Exception: JSON::GeneratorError: 836: Infinity not allowed in JSON
```

looking at the trace it looks like `ActiveSupport::JSON::Encoding` is receiving `Hash` not `Hash.as_json`

**Comment by groyoh** [comment]
Nice catch. Though, I'm not sure if this should be considered an AMS bug but rather an ActiveSupport bug. If you take a look at [this gist](https://gist.github.com/groyoh/d6a29edf266ef9b2e370fdbc4c9032a3), you'll see that as long as you redefine `as_json` to return a `Hash` with an `Float::INFINITY` value a `GeneratorError` is raised. This is because [`jsonify`](https://github.com/rails/rails/blob/v5.0.0.1/activesupport/lib/active_support/json/encoding.rb#L82) does not call `as_json` on `Float::INFINITY` since it is a `Float` e.g. `Numeric`. Would you mind opening an issue at https://github.com/rails/rails/issues/new to figure out if this is the intended behavior?

A easy way to fix your issue would be to change [this method](https://github.com/rails-api/active_model_serializers/blob/v0.10.2/lib/active_model_serializers/adapter/base.rb#L59) and [this method](https://github.com/rails-api/active_model_serializers/blob/v0.10.2/lib/active_model/serializer.rb#L185) to:

```ruby
def as_json(options = nil)
  serializable_hash(options).as_json
end
```

but there might be a performance impact though (not sure about this). You could probably monkey-patch AMS in the meantime if that's an acceptable solution for you. These two methods are very unlikely to change in my opinion.

**Comment by igagnidz** [comment]
I agree. I will open the issue there too. Is it ok to post the link to the issue in rails here for the reference?

**Comment by beauby** [comment]
@igagnidz Certainly.

**Comment by tomfast** [comment]
@ocha did you end up creating an issue for that exception? Just stumbling upon this as well and would appreciate the link.

**Comment by ocha** [comment]
@tomfast I think it was fixed here https://github.com/rails/rails/issues/26877

**Comment by tomfast** [comment]
Thanks @ocha !
