### ISSUE TITLE
When :json adapter is configured, `as_json` output has no root key

### ISSUE THREAD

**Issue by Sporky023** [rails-api/active_model_serializers#1965]
#### Expected behavior vs actual behavior

Expected: Calling `PostSerializer.new(Post.last).as_json` should return a hash with a `:post` key,  i.e. expected to have root key, as described in [Adapters documentation](https://github.com/rails-api/active_model_serializers/blob/master/docs/general/adapters.md#adapters)

Actual: Calling `PostSerializer.new(Post.last).as_json` returns a hash with keys `:id`, `:title`, and `:body` (i.e. has no root key)  

#### Steps to reproduce

I've built a sample app that demonstrates this bug at https://github.com/Sporky023/ams_adapter_config_bug/commits/master  

Steps to reproduce are represented by the commits in that app, followed by:  

`rails c`  
`Post.create!(title "test title", body: "test body")`
`PostSerializer.new(Post.last).as_json`  

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*:  

I believe I am on tag 0.10.2.  I am not sure how to determine which tag or commit ref I'm on.  

Here's the output of `bundle list active_model_serializers` within my sample app:
`/Users/<my username>/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/active_model_serializers-0.10.2`

Output of `ruby -e "puts RUBY_DESCRIPTION"`:  `ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]`

OS Type & Version:  OSX Version 10.10.5 (14F27)

Integrated application and version *(e.g., Rails, Grape, etc)*:   Rails 4.2.5

#### Backtrace
*(e.g., provide any applicable backtraces from your application)*
N/A

#### Additonal helpful information

Gemfile.lock:  https://github.com/Sporky023/ams_adapter_config_bug/blob/master/Gemfile.lock

**Comment by bf4** [comment]
@Sporky023 this is because calling `as_json` on a serializer does not use an adapter.  The adapter is used when serializing via `SerializableResource`.

In the future, I think the serializer `as_json` should behave like the Rails `as_json`, that is include the root if configured or passed in. This would also consolidate much of the two adapters, some work that's been ongoing.

If you're up to help update the docs for other people that come across this or help with implementing this, that would be great and I'm happy to help.

Closing as resolved, but please feel free to comment or reopen, and be sure to followup with your resolution.
