### ISSUE TITLE
rails deploy

### ISSUE THREAD

**Issue by Chem-Lab** [rails-api/active_model_serializers#1980]
#### Expected behavior vs actual behavior
I am using rails 5 api with AMS 0.10.2
I use JSON to work with restkit
I need more than one level, 
my initializer:
 ActiveModelSerializers.config.adapter = :json
ActiveModelSerializers.config.default_includes = '**'

One or more levels works fine on my development machine.

On deploy only one level works as expected
If there are more levels all the attributes are serialized.

What can I do?

**Comment by bf4** [comment]
Closing due to insufficient information to easily help.

Please review the requested information in our [issue template](https://github.com/rails-api/active_model_serializers/blob/master/.github/ISSUE_TEMPLATE.md) and reopen with the additional information, or any questions and comments you may have.

Thanks for your help, and thanks for making this issue.
