### ISSUE TITLE
How to disable AMS in all controllers and do it manually?

### ISSUE THREAD

**Issue by GuskiS** [rails-api/active_model_serializers#2053]
How to disable AMS in all controllers and do it manually? At the moment, it is trying to serialize everything for me. How to disable that?

Rails 5.0.1, AMS 0.10.4.

**Comment by bf4** [comment]
Closing due to insufficient information to easily help.

Please review the requested information in our [issue template](https://github.com/rails-api/active_model_serializers/blob/master/.github/ISSUE_TEMPLATE.md) and reopen with the additional information, or any questions and comments you may have.

Thanks for your help, and thanks for making this issue.

**Comment by GuskiS** [comment]
It wasn't like an issue, just a question. For example, I have code that returns me json with various keys which I use in controller, but AMS tries to parse all of those keys. I wish I could use this gem explicitly - parsing only things I want, not everything in `render json: my_hash`. Is it doable? Basicly I don't want rails controller interaction "magic".

**Comment by bf4** [comment]
I don't know what you've tried. Are you asking for free help because you didn't read the docs, or have you put like 8 hours into it and gave up?  Are you sharing the burden?

**Comment by polarlights** [comment]
@GuskiS U can set the AMS adapter to be `attributes`. If U want to render some objects to be jsonapi style, just do it like this: `render json: objects, adapter: :jsonapi`.

**Comment by bf4** [comment]
There's no magic... but in any case, it will always ignore a string.  So, just dump your object to JSON (often by calling to_json)
