### ISSUE TITLE
Nested serializers dont work?

### ISSUE THREAD

**Issue by 9mm** [rails-api/active_model_serializers#2056]
I've tried for awhile to get this working and I can't figure out why the TestSerializer is completely ignored. I've tried writing it all the different ways I can think of. It just ignores the inner serializer

```
class Units::ShowSerializer < UnitSerializer

  has_one :tenant do
    object.user
  end

  has_many :invoices do
    object.invoices.joins('LEFT OUTER JOIN "payments" ON "payments"."invoice_id" = "invoices"."id"')
  end

  class UserSerializer < ActiveModel::Serializer
    attributes :id, :first_name, :last_name, :email, :phone, :created_at
  end

  class InvoiceSerializer < ActiveModel::Serializer
    attributes :id, :generated_at, :due_at

    has_one :payment, serializer: TestSerializer do
      object.payment
    end

    class TestSerializer < ActiveModel::Serializer
      attributes :id, :method
    end
  end

end
```

**Comment by bf4** [comment]
Closing due to insufficient information to easily help. Deep nesting is something AMS does not recommend, but does allow. See the deep nesting category I've added.

Please review the requested information in our [issue template](https://github.com/rails-api/active_model_serializers/blob/master/.github/ISSUE_TEMPLATE.md) and reopen with the additional information, or any questions and comments you may have.

Thanks for your help, and thanks for making this issue.
