### ISSUE TITLE
Rendering an empty array with JSON Adapter

### ISSUE THREAD

**Issue by jmeredith16** [rails-api/active_model_serializers#2210]
Hello all,
#### Explanation and Expected behavior vs actual behavior
I have an Array of objects called `clusters`.  A Cluster does not have a serializer, as I am using only AMS to serialize objects in my API, not this part of my codebase.

I expect that when I render my empty clusters array, I get back an empty array `[]`, but I am actually getting back `{"":[]}`.  This is causing some frontend issues, resulting in an error unrelated to AMS.

Removing `ActiveModelSerializers.config.adapter = :json` from my initializer causes the empty clusters Array to respond with `[]` as expected.

With ActiveModelSerializers.config.adapter = :json
```
[2] pry(#<ClustersController>)> @clusters
=> []
[3] pry(#<ClustersController>)> render json: @clusters
I, [2017-10-26T15:37:33.504075 #67524]  INFO -- : Rendered ActiveModel::Serializer::CollectionSerializer with ActiveModelSerializers::Adapter::Json (2.63ms)
=> ["{\"\":[]}"]
```

With no AMS adapter specified in my initializer (ie, :attributes)
```
[2] pry(#<ClustersController>)> render json: @clusters
I, [2017-10-26T15:41:04.020091 #67607]  INFO -- : Rendered ActiveModel::Serializer::CollectionSerializer with ActiveModelSerializers::Adapter::Attributes (0.25ms)
=> ["[]"]
```

- Is `{"":[]}` the expected response when rendering an empty Array while using AMS?
- Is there another way to pass this variable through untouched by AMS?

#### Environment 
active_model_serializers: 0.10.6 - dff621e1744d37672ccba13f8e4b64dcc5b135c3
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
OS X El Capitan, V10.11.3
Rails 4.2.6

#### Additional helpful information
As a solution/workaround, I used `render json: @clusters.to_json`, which returns the empty Array as expected.
Regardless of adapter type, if I have data in my `clusters` variable it will render correctly.

Possibly related: 
- https://github.com/rails-api/active_model_serializers/issues/945
- https://github.com/rails-api/active_model_serializers/tree/0-10-stable#primitive-handling

Thanks for your time

**Comment by bf4** [comment]
@jmeredith16  Sorry for the bug.

One thing that's kind of interesting about this is that if your `@clusters` object were an active model object,  it would be serialized as `clusters: []`. That's what AMS is wanting to do, I believe that if you passed in an `each_serializer: ClusterSerializer` option, you'd get that.  The problem is that AMS has no way to know what the `root` element is for an empty array, and the JSON adapter adds roots for everything.  You could also try passing in `root: "clusters"` and it should do the right thing, I think.

The source code of the problem is in https://github.com/rails-api/active_model_serializers/blob/v0.10.6/lib/active_model/serializer/collection_serializer.rb#L30-L50

I do think that it is a bug to serializer `"" => []` and shoudl probably raise a meaningful exception `Unable to determine root of []. Please pass in a root or each_serializer option, render a JSON string`

**Comment by jmeredith16** [comment]
@bf4 Thanks for the reply.  That all makes a lot more sense.

Are there instances where returning a `nil` key from `json_key` is desired?  Or would throwing an UndeterminableJsonRootError be preferable?  Specifically, I'm referring to the tests located at https://github.com/rails-api/active_model_serializers/blob/v0.10.6/test/collection_serializer_test.rb#L92-L102, and whether or not they should be changed to something like:
```
def test_json_key_with_resource_without_name_and_no_serializers
  serializer = collection_serializer.new([])
  assert_raise UndeterminableRootError do
    serializer.json_key
  end
end
```

**Comment by bf4** [comment]
Sounds good .  Probably argument error, cannot infer root key from collection type. Please specify the root or serializer or give the collection the .... property

B mobile phone

**Comment by bf4** [comment]
related: https://github.com/rails-api/active_model_serializers/issues/1745

**Comment by sferik** [comment]
I ran into this issue recently and solved it with the following code:

```ruby
if @clusters.blank?
  render(plain: '[]', content_type: 'application/json')
else
  render(json: @clusters)
end
```

**Comment by bf4** [comment]
@sferik That's certain an acceptable solution, but shouldn't be necessary

Also, if you are forced into a scenario like this, you may prefer `render json: '[]'` since AMS and Rails ignore strings in the JSON renderer.
