### ISSUE TITLE
arrayserializer vs each_serializer rails?

### ISSUE THREAD

**Issue by dbzamt** [rails-api/active_model_serializers#2227]
#### Steps to reproduce
*(e.g., detailed walkthrough, runnable script, example application)*

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: 

Output of `ruby -e "puts RUBY_DESCRIPTION"`: 

OS Type & Version: 

Integrated application and version *(e.g., Rails, Grape, etc)*: 

#### Backtrace
*(e.g., provide any applicable backtraces from your application)*

#### Additonal helpful information
*(e.g., Gemfile.lock, configurations, PR containing a failing test, git bisect results)*

**Comment by bf4** [comment]
Closing due to insufficient information to easily help.

Please review the requested information in our [issue template](https://github.com/rails-api/active_model_serializers/blob/master/.github/ISSUE_TEMPLATE.md) and reopen with the additional information, or any questions and comments you may have.

Thanks for your help, and thanks for making this issue.
