### ISSUE TITLE
include not working

### ISSUE THREAD

**Issue by silentlight** [rails-api/active_model_serializers#2229]
Does anyone know if `include` option in controllers still work with `0.10.7` version of AMS? I am using :json adapter with `ActiveModelSerializers.config.default_includes = ''`.

Thanks

**Comment by bf4** [comment]
@silentlight There's a lot of info missing from your question.  Are you asking about deep nesting of relationships? And are you trying to prevent it? i.e. what are you trying to do?

Closing due to insufficient information to easily help.

Please review the requested information in our [issue template](https://github.com/rails-api/active_model_serializers/blob/master/.github/ISSUE_TEMPLATE.md) and reopen with the additional information, or any questions and comments you may have.

Thanks for your help, and thanks for making this issue.
