### ISSUE TITLE
Override serializable_hash

### ISSUE THREAD

**Issue by ulugbekov** [rails-api/active_model_serializers#2233]
Hi,

I am trying to include relationships dynamically based on role. When rendering single record, it is working as expected. Collection rendering is not including relationships. I see, there is a active model collection serializer. What overrides, I have to make in order to get include relationships to be included dynamically.

Thanks

  def serializable_hash(adapter_options = nil, options = {}, adapter_instance = self.class.serialization_adapter_instance)
    adapter_options ||= {}

    if current_user.id == object.id
      adapter_options[:include] = current_user.permitted_includes :user
    else
      adapter_options[:include] = current_user.permitted_includes object.role.slug, :roles
    end

    super(adapter_options, options, adapter_instance)
  end

**Comment by bf4** [comment]
Closing due to insufficient information to easily help.

Please review the requested information in our [issue template](https://github.com/rails-api/active_model_serializers/blob/master/.github/ISSUE_TEMPLATE.md) and reopen with the additional information, or any questions and comments you may have.

Thanks for your help, and thanks for making this issue.
