### ISSUE TITLE
[ams] :test_render. Invalid JSON document.

### ISSUE THREAD

**Issue by wonderer007** [rails-api/active_model_serializers#2248]
I am getting 

> [ams] :test_render. Invalid JSON document.

when I run
`bundle exec ruby benchmark.rb` 

on Ubuntu 16.04 with ruby-2.3.0

Thanks

**Comment by bf4** [comment]
Closing due to insufficient information to easily help.

Please review the requested information in our [issue template](https://github.com/rails-api/active_model_serializers/blob/master/.github/ISSUE_TEMPLATE.md) and reopen with the additional information, or any questions and comments you may have.

Thanks for your help, and thanks for making this issue.
