### ISSUE TITLE
Rails 4.2.1 not using serializer instead it returns string

### ISSUE THREAD

**Issue by israelcoper** [rails-api/active_model_serializers#2274]
After upgrading from rails 4.1.9 to 4.2.1, the controllers does not returns the expected json using the serializer instead it returns something like this **"#\u003cUserSerializer:0x007fb8c12d1488\u003e"**.

Here's the content of my Gemfile:
```
ruby "2.2.10"
gem "rails", "4.2.1"
gem 'active_model_serializers', github: 'rails-api/active_model_serializers', branch: '0-9-stable'
```

**NOTE:** I did try using all version from 0.8.0 to 0.10.7 and still it gives me string.

Please help. Thanks.

**Comment by bf4** [comment]
Closing due to insufficient information to easily help.

Please review the requested information in our [issue template](https://github.com/rails-api/active_model_serializers/blob/master/.github/ISSUE_TEMPLATE.md) and reopen with the additional information, or any questions and comments you may have.

Thanks for your help, and thanks for making this issue.

**Comment by stefanahman** [comment]
@israelcoper Have you solved it?

**Comment by bf4** [comment]
@stefanahman please make a new issue, though it probably is problem with either how you're using AMS or a json serialization gem you've installed

**Comment by stefanahman** [comment]
@bf4 Reading https://github.com/rails-api/active_model_serializers/issues/2252, it is probably `oj` in my case. Thanks.
