### ISSUE TITLE
Versioning support

### ISSUE THREAD

**Issue by pirvudoru** [rails-api/active_model_serializers#2343]
#### Expected behavior vs actual behavior
According to: https://semver.org/ #3:
```
PATCH version when you make backwards-compatible bug fixes.
```
I expect patches to not break the app. 

But...
![image](https://user-images.githubusercontent.com/2707601/61363491-c2499200-a88c-11e9-8d21-7c3cf69c2bfc.png)

This library is a nightmare to work with when it comes to updating the version, and it has been this way since v 0.7.x (when we started using it - huge mistake).

**Comment by pethron** [comment]
Same problem.
It's not possible to break things in a minor version upgrade, at least run the goddamn tests.

**Comment by pethron** [comment]
<img width="1378" alt="Screenshot 2019-07-17 at 15 40 33" src="https://user-images.githubusercontent.com/12462586/61380252-532e6680-a8a9-11e9-9ece-23cb166cee03.png">

What the f*** is this???
Next time use https://github.com/auchenberg/volkswagen

**Comment by FeminismIsAwesome** [comment]
Y'all should calm down. A) your test suite caught them, and while annoying that's easy enough to not upgrade or make an issue about it, it's an open source project you can contribute to since it needs love and support.
B) If you're using an undocumented feature and the standard docs suggest root as string anyways; it was easy for us to correct the issues we saw and move on. Or are you saying we should be testing things we don't know people care about? Once the issue was seen, they fixed it and added a test so it's not like they don't test they just don't do it the way you do.

**Comment by pirvudoru** [comment]
:wave:

**Comment by wasifhossain** [comment]
nevertheless I agree with you @pirvudoru :+1: 

should have followed the semver strictly. unfortunately we are not quite sure at this point in time if v1 would be released in near future, from which it would be easier to maintain the semver policy

**Comment by bf4** [comment]
@wasifhossain 0.10 is supposed to be stable.  AMS is older than semver.  There shouldn't be breaking changes with 0.10.x. Just like rake of old, think of 0.10.x and 10.x

**Comment by bf4** [comment]
@pethron I think you and @pirvudoru may be looking at master https://github.com/rails-api/active_model_serializers/blob/bd40fe68f0ba7332a4b86c793149ebbcd207ca9f/.travis.yml  the 0.10.x release comes from the 0-10-stable branch

**Comment by wasifhossain** [comment]
@bf4 thanks for the point.

in that case, should we consider a new version 0.10.x.y, where y would be for patch.

also what would be the policy for breaking changes like #2341, which was introduced in `0.10.10` since #2223. should we release 0.10.11 or 0.10.10.1
