### ISSUE TITLE
render_to_string serialization

### ISSUE THREAD

**Issue by BKDruby** [rails-api/active_model_serializers#2372]
Could somebody help me?

I want to use `render_to_string` with options like
{:json=>"[array of objects]", :each_serializer=>AccountSerializer, :meta=>{:current_page=>1, :next_page=>nil, :prev_page=>nil, :total_pages=>0, :total_count=>0}, :filtered_by_category=>nil, :filter_by_locale__id=>nil}

But it requires `request` object. And I use it outside of controller.

So I want to return same response like {accounts: [....], meta: {....} }  depends on options, but without request.

**Comment by bf4** [comment]
Closing due to insufficient information to easily help.

Please review the requested information in our [issue template](https://github.com/rails-api/active_model_serializers/blob/master/.github/ISSUE_TEMPLATE.md) and reopen with the additional information, or any questions and comments you may have.

`render_to_string` is a controller method.  AMS has documentation for usage outside of controllers.

Thanks for your help, and thanks for making this issue.
