### ISSUE TITLE
Global root option

### ISSUE THREAD

**Issue by whatyoubendoing** [rails-api/active_model_serializers#298]
Using the global root option in an initialiser descent work in rails 4

```
ActiveModel::ArraySerializer.root = false
```

**Comment by lucasdavid** [comment]
@vanstee's solution doesn't seem to work anymore :-(

**Comment by bf4** [comment]
@lucasdavid please consider that you just commented on an issue that was closed as resolved *five* (5!) years ago and I can't even confirm 1) that you're referring to the same version the issue is related to or 2) what you tried. I'm going to lock this issue now. Please open an new issue and follow the guidelines.
