### ISSUE TITLE
polymorphic has_many associations seem to be broken

### ISSUE THREAD

**Issue by jonah-williams** [rails-api/active_model_serializers#366]
When I define a polymorphic `has_many` association I expect the serializer to produce an array of hashes each of which looks like the output of a polymorphic `has_one` association. Instead the `polymorphic: true` option seems to have no effect.

Issue #13 seems to suggest that this should work. However none of the polymorphic tests use `has_many` and `Association::HasMany` does not consider the `polymorphic` option as `Association::HasOne` does. Am I missing something?

See https://github.com/carbonfive/active_model_serializers/tree/has_many_support_polymorphic_associations for example failing tests.

I'll see if I can provide a fix in a pull request.

cc @alexmouton

**Comment by cmrd-senya** [comment]
Sorry for the bringing up an old topic, but I didn't want to create a new issue since I didn't know if it is a bug or a feature. `has_many`/`polymorphic` doesn't seems not to work on AMS `0.10.6` for me right now. I created [a question on stackoverflow](https://stackoverflow.com/questions/45394553/activemodel-serializer-0-10-has-many-polymorphic-association) (as suggested by the readme) describing my case, but for the case it's an issue that needs some care from developers I leave this note here.
