### ISSUE TITLE
Serializer fails when used with class extending ActiveModel::Model

### ISSUE THREAD

**Issue by chriskilding** [rails-api/active_model_serializers#520]
When I use AMS in my project, all 'real' AR models work fine with the serialisers, but there are 2 problems using it with a virtual model that inherits from ActiveModel::Model:
1. Controller does not use the AMS serialiser unless explicitly specified
   I have to specify it with `render json: foo, serializer: FooSerializer...` to make this work.
2. After serialiser is explicitly defined, using it fails with the following trace:

```
NoMethodError:
       undefined method `read_attribute_for_serialization' for #<Foo:0xblah>
     # (eval):3:in `_fast_attributes'
     # <controller that called `render json: foo...`>  
```

Using AMS v0.8.1 on Rails 4.0.2 / Jruby 1.7.9

Is this just a bug in the way I am using AMS, or does it not yet support virtual models?

**Comment by ZiaMM** [comment]
In version 0.09, I added the above  Same error.  Tried this line too: 
include ActiveModel::Serializers::JSON
... same error.
Moved to Version 0.10 rc4, and now either of these seem to work.  Sill doesn't work - likely due to different syntax needed for this version - but I can make this error appear and disappear with either of the above "include" options.

**Comment by bf4** [comment]
@ZiaMM Please open a new issue (and check the docs)
