### ISSUE TITLE
undefined method `belongs_to`

### ISSUE THREAD

**Issue by colby-swandale** [rails-api/active_model_serializers#648]
I am using rails 4.1.4 with the latest active_model_serializers from rubygems.

In the documentation there are examples that show the usage of `belongs_to` but when i try it myself rails complains the method is undefined. Am i missing something? Here is Serializer class i am trying this on.

```
class UserSerializer < ActiveModel::Serializer
  attributes :first_name, :last_name, :email, :state, :uuid
  belongs_to :tenant
end
```

**Comment by mrusa** [comment]
I have got the same problem, using Ruby 2.1.2, Rails 4.1.9 and active_model_serializers 0.9.2 on nginx with passenger.

On my local machine everything works fine but on production there is the above-mentioned error. The passenger error page shows im using active_model_serializers 0.9.2, so there's the correct version running on production. Im not sure what im doing wrong?

My serializers look like the following:

```ruby
class InvoiceSerializer < ActiveModel::Serializer
  attributes :id, :invoice_number, :locked, :active

  has_many :invoice_positions
end
```

```ruby
class InvoicePositionSerializer < ActiveModel::Serializer
  attributes :id, :invoice, :quantity

  belongs_to :invoice
end
```

**Comment by pferdefleisch** [comment]
I just double checked and it turns out `belongs_to` doesn't exist.
If you look at the `0.9.2` README [here](https://github.com/rails-api/active_model_serializers/tree/0-9-2)
you will see this

> Serializers are only concerned with multiplicity, and not ownership. belongs_to ActiveRecord associations can be included using has_one in your serializer.

So think about what you are really doing with your `belongs_to`
If you will never be using `InvoicePositionSerializer` by itself then it is unnecessary
If you will, then use a `has_one` like @chabgood mentioned

**Comment by colby-swandale** [comment]
i'm going to go ahead and close this issue.

**Comment by mrusa** [comment]
Ah ok, so i was reading the wrong readme.. I was just irritated that everything worked on my local environment. Thanks for your help

**Comment by gnapse** [comment]
The README on master (the one that is shown when someone visits the repository's home page, still shows `belongs_to` in an example, and no example with `has_one`.

**Comment by jimboslicethat** [comment]
I know this is a closed issue, but has anyone experienced problem with the has_one method behaviour changing in production? I understand that we are supposed to use has_one instead of belongs_to. I'm just wondering if anyone has run into problems with has_one. See my stackoverflow question for examples: 

http://stackoverflow.com/questions/33111605/why-does-grape-api-activemodelserializer-has-one-break-in-production?noredirect=1#comment54037795_33111605
