### ISSUE TITLE
Issue with the latest upgrade 0.9.1

### ISSUE THREAD

**Issue by kapso** [rails-api/active_model_serializers#746]
After the upgrade `render json: { ok: true }` is returning this `{"sessions"=>[["ok", true]]}` where `sessions` is the name of the controller. Its weird.

adding a `to_json` fixes it `render json: { ok: true }.to_json` ??

**Comment by kurko** [comment]
We lost many, many good commits (almost 4 months) doing this. `0.9.1` was good except for 1 commit (#665 ?). We had support for Rails 4.2 and a bunch of other fixes.

Could someone kindly pick the 0.9.1 tag, revert just that one commit and open a PR? I really can't do this because I don't use `0.9` :( but your work will help tons of people.

**Comment by nateberkopec** [comment]
@kurko https://github.com/rails-api/active_model_serializers/pull/775 but the merge isn't clean

**Comment by kurko** [comment]
s/775/776

**Comment by kurko** [comment]
Could everyone here please test #776? It's basically the 0.9.1 (full of fixes) minus the problematic commit that breaks the universe. If #776 works on your apps, then it could potentially become 0.9.3.

**Comment by recurrence** [comment]
Wouldn't this be better than 0.9.2 even if there is a small regression or two?  Seems to be working fine for me if this naive and completely unscientific data point helps any :)   Ship It! :)

**Comment by kurko** [comment]
Released https://rubygems.org/gems/active_model_serializers/versions/0.9.3. It's basically 0.9.1 (tons of bugfixes) minus the commit that caused tons of regressions. Please test and let us know how it goes :grin:
