### ISSUE TITLE
0.9.3 boolean attrs returns method missing

### ISSUE THREAD

**Issue by colinreidbrown** [rails-api/active_model_serializers#845]
in 0.9.3 the following returns method missing where previous versions did not:
```
class ThingSerializer < ActiveModel::Serializer
attributes :uses_thing?

def uses_thing?
  true
end
end
```
```
def uses_thing
  true 
end  
```
would also return the declared attr before but 0.9.3 returns the method name instead of the declared attr name fyi

**Comment by colinreidbrown** [comment]
as a clarification it is not specifically boolean but attr / methods with atrailing "?" in the name

**Comment by kurko** [comment]
Can you check 0.9-stable branch

**Comment by kurko** [comment]
Could you check the 0.9-stable branch, whether this was fixed or not already? We're about to release 0.9.4 via https://github.com/rails-api/active_model_serializers/issues/871 and I'd love to know if that was fixed.

If not, do you think you can venture a PR with a fix?

**Comment by prasadsurase** [comment]
Checked with and without method name using '?'. This is broken on '0-9-stable' too.
// method using '?'
0-9-stable, 0.9.3, 0.9.1  => error: undefined method
0.9.2, 0.9.0 => returns attribute as expected(with '?').

// method without using '?'
0-9-stable, 0.9.2, 0.9.0 => error: undefined method
0.9.3, 0.9.1 => returns method name as attribute

**Comment by prasadsurase** [comment]
Further digging revealed that the functionality to autostrip question mark was introduced in [#662] (https://github.com/rails-api/active_model_serializers/pull/662/files) which was in response to [#605](https://github.com/rails-api/active_model_serializers/issues/605) issue. 

I think that we shouldn't autostrip any characters from the attributes specified in the serializer since user can always add own logic to get custom attributes.

**Comment by ace-subido** [comment]
Just posting here since it has a label "Needs bug verification". I might have the same case, I also ran into something like this when we allowed `active_model_serializer, "~> 0.9"` on our Gemfile instead of nailing it at `0.9.0`.

```
# Serializer
class SomethingSerializer < ActiveModel::Serializer
  attributes :some_bool_attribute?
end

# Class
class Something
    # has an attribute called `some_bool_attribute`
  end
end
```

Tests that expected the serializer hash to contain a "some_bool_attribute?" key are currently failing.
