### ISSUE TITLE
Serialize self-children of a model

### ISSUE THREAD

**Issue by riccardoat1** [rails-api/active_model_serializers#881]
Hi, I'm using the ancestry gem for have self recoursive children of a model.
Example: Tasks has many sub tasks(that is always Task model)
All works well, the only problem is:
While for the parent is show also the assocation object user, for the children it doesn't show the user object, but only show the user_id

Why ?
my code is: https://gist.github.com/riccardoa/001980cdc6202d3771f3
I've also tried to do:
```has_many :children, serializer: TaskSerializer```
but doesn't change anything
I've also exposed my problem on StackOverflow (http://stackoverflow.com/questions/29830535/serialize-json-association-for-children-of-a-model)

it's maybe a bug/limitation of active_model_serializers or I'm doing wrong ?

Thanks.

**Comment by danielevans** [comment]
What version of active_model_serializers are you using?

**Comment by riccardoat1** [comment]
@danielevans master I think...
gem 'active_model_serializers', github: 'rails-api/active_model_serializers'

**Comment by bf4** [comment]
@riccardoat1 if you have a Gemfile.lock, copy the ams section near the top, has about 3 or 4 lines, including the git url and hash ref and paste here :)

**Comment by groyoh** [comment]
I think this is the expected behaviour:

**Comment by groyoh** [comment]
@riccardoat1  I don't know if it is the expected behavior but json adapter only serialize the attributes of the associations (see [here](https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model/serializer/adapter/json.rb#L17-36)). So associations of associations won't get serialized.

@joaomdmoura if this is the expected behaviour, then this is not a bug.

**Comment by joaomdmoura** [comment]
@groyoh Indeed, this is the expected behaviour. And probably the most common case.
@riccardoat1 You can work around this by overriding the user relationship with a method in the serializer. Would be nice to know what version of AMS you are using, you can check it into your Gemfile.lock as @bf4 pointed out.

**Comment by bf4** [comment]
Propose closing as stale

**Comment by joaomdmoura** [comment]
Agreed @bf4
