### ISSUE TITLE
Side loading doesn't work in 0.10.0.rc1 (non-JSONAPI)

### ISSUE THREAD

**Issue by blakemcintyre** [rails-api/active_model_serializers#899]
I've been trying to setup side loading using the standard adapter, (not JSONAPI), and have been unable to generate any embedded data. This works in 0.8.1 but the issue stated in https://github.com/rails-api/active_model_serializers/issues/377 has lead me to trying 0.10.x. When I tried using the JSONAPI adapter I was able to get included/linked data.

The following is the basic setup I've been testing with:
```ruby
class ArticleSerializer < ActiveModel::Serializer
  attributes :id, :title, :published_at

  has_many :authors, embed: :ids, serializer: UserSerializer

  url :article
end

class UserSerializer < ActiveModel::Serializer
  attributes :id, :name

  url :user
end


class Article < ActiveRecord::Base
  has_many :article_authors
  has_many :authors, through: :article_authors, class: User
end

class ArticleAuthor < ActiveRecord::Base
  belongs_to :article
  belongs_to :author, class: User
end

class User < ActiveRecord::Base
  has_many :article_authors, foreign_key: :author_id
  has_many :articles, through: :article_authors
end


class ArticlesController < ApplicationController
  def index
    render json: Article.last(3), root: :articles, include: 'authors'
  end
end
```

**Comment by henrymazza** [comment]
+1

I’m using ember-data, is there a way to achieve the same format I had with 0.8.x? That is with `embed :ids` and associations sideloaded?

**Comment by meltingice** [comment]
This is currently the only thing stopping me from upgrading to 0.10.x. In order to maintain the same API format and prevent breaking our client, I need to be able to sideload objects in the root.

**Comment by henrymazza** [comment]
Now I hear that ember data is aiming to the same JSONAPI format that AMS 0.10.x is defaulting to. Plus it should ship a compatible beta version somewhere in June. 

Can someone confirm this? 

Enviado de um aparelho móvel.

**Comment by meltingice** [comment]
For what it's worth, we aren't using the JSONAPI spec, but we still need to sideload data. I've been playing around with the JSON serializer in order to add the functionality back. I'll see if I can get a proof-of-concept together.

**Comment by joaomdmoura** [comment]
Hey everybody, I'm just jumping in to let you know that I'm following this and will try to give it a closer look on the weekend. @meltingice would be awesome to have some prof-of-concept :smile: 
Thank y'all! :heart:

**Comment by benwoodward** [comment]
+1

**Comment by saneshark** [comment]
I've been using a decorator pattern, decorating the collection with an instance variable that has my sideloaded query set and group_by(:foreign_key_id), then my individual decorator overrides the association method, doing a hash lookup based on the sideloaded hash or super if the hash was not passed in as part of the collection's context. For me this is necessary no matter what since my API consumer needs to pass in parameters limiting the scope of the association as well (has_many).

**Comment by jtippett** [comment]
+1

**Comment by joaomdmoura** [comment]
@henrymazza confirmed. Ember, as far as I know, is moving forward to use JSON-API. We had to remove it as default because of a WIP Rails integration, but it's already supported and extremely easy to use.

**Comment by ahmeij** [comment]
We are not using ember, however we are using 0.9 with embed: ids, and sideloading. this works quite well for us however since we desperately need caching we'd like to upgrade to 0.10.

As we have multiple clients for our api based on the above model updating the output to be compatible with json_api is a ways off.

Is there a way to upgrade? // did someone make a json_legacy adapter maybe? I think this is definitely needed to avoid breaking all api's out there when upgrading to 0.10

I will take a stab at making a legacy adapter if none exists

**Comment by NullVoxPopuli** [comment]
I have a pull request #1088 which I hope addresses this for most people

**Comment by joaomdmoura** [comment]
Nice to see this being bumped! I'll check both PRs @ahmeij && @NullVoxPopuli

**Comment by remear** [comment]
Looks like #1088 + #1111 + #1114 resolved this

**Comment by bf4** [comment]
Also see #1127
