### ISSUE TITLE
Clarify usecase for the 2 JSON adapters

### ISSUE THREAD

**Issue by akshayrawat** [rails-api/active_model_serializers#900]
`active_model_serializers` has two adapters `JSON` and `JSON-API`. It is not clear when to use one over the other, or to just follow one by some convention.

It would be really nice if the README mentioned the use case of one over the other.

**Comment by joaomdmoura** [comment]
Hi @akshayrawat indeed, your are right! We are already addressing it! I'm putting together a PR that will make ```JSON-API``` the default adapter. :smile: Because of that I'm closing it.
Just for the record we really want to make ```JSON_API``` a convention, we believe it's a great implementation that can help a lot of different technologies.

**Comment by akshayrawat** [comment]
:+1:
