### ISSUE TITLE
docs for "default" association loading

### ISSUE THREAD

**Issue by nruth** [rails-api/active_model_serializers#928]
This is w.r.t the master branch.

```
The has_many, has_one, and belongs_to declarations describe relationships between resources. 
By default, when you serialize a Post, you will get its Comments as well.
```

What's the idiomatic way to change this default?

I'm currently thinking I need to provide 2 serializers in my controller, one for my array collection (index, so it doesn't side-load and get slow), and one for my singular collection (show)?

If that's the expected way then this isn't actually a default (of associations in a serializer), as it isn't configurable, and I'd like to edit the readme to reflect that?

**Comment by nruth** [comment]
I see this isn't ready to use yet so went for 0.8 branch for now, where there's the embed :ids option & other bits and pieces like that.

**Comment by joaomdmoura** [comment]
Hey @nruth sorry for take some while to check this issue :smile: 
No this **is not** the default behaviour. Someone might have miss typed it. 
Your serializer will return its relationships only when declared.
I would recommend you to use 0.10rc1, not only because I believe is way better than older version but also to help us into the process of validating it. :smile:
