### ISSUE TITLE
NoMethodError (undefined method `fetch_or_store' for #<ThreadSafe::Cache:0x007fcf70821378>)

### ISSUE THREAD

**Issue by eliduke** [rails-api/active_model_serializers#929]
I just upgraded my AMS gem to `0.10.0.rc1` in hopes of getting some better caching functionality. I am trying to cache some App Label and the serializer there looks like this:

```
class AppLabelSerializer < ActiveModel::Serializer
  cache key: 'app_label', expires_in: 3.hours
  attributes :id, :key, :label, :label_plural

  def key
    object.app_label_dictionary.key
  end

end
```

And then I hit one of the AppLabel end points with PostMan and I get this error:

```
NoMethodError (undefined method `fetch_or_store' for #<ThreadSafe::Cache:0x007fcf70821378>):
  app/controllers/v1/app_labels_controller.rb:22:in `auth_index'
```

I checked `app_labels_controller.rb` on line 22 and it is this method:

```
def auth_index
  render json: AppLabel.non_event
end
```

Which is calling an AppLabel scope:

```
scope :non_event, -> {joins(:app_label_dictionary).where(app_label_dictionary: {event_label: false} )}
```

I'm not familiar enough with AMS caching or Rails' Threadsafe elements to know what's going on here.

Any thoughts?

**Comment by eliduke** [comment]
I tried some more troubleshooting and stopped calling the scope and instead just called `AppLabel.all` and I still get the same error.

**Comment by groyoh** [comment]
Which version of Rails do you use?

**Comment by eliduke** [comment]
4.0.5

**Comment by joaomdmoura** [comment]
@eliduke what's the ```thread_safe``` version?

**Comment by groyoh** [comment]
@joaomdmoura there is something weird going on here. Rails 4.0.x should require thread_safe ~> 0.1 (see [here](https://github.com/rails/rails/blob/v4.0.5/activesupport/activesupport.gemspec)). When I run `gem install thread_safe --version "~> 0.1"`, it will install 0.3.5. When I run `gem install thread_safe --version "0.1"`, it will install 0.1.0. When I run `gem install thread_safe --version "~> 0.1.0"`, it will install 0.1.3. Looks like a bug from rubygem.

Maybe on his configuration Rails was installed with thread_safe 0.1.x and therefore does not have this method.

**Comment by eliduke** [comment]
`gem list` says `thread_safe (0.3.5, 0.3.4, 0.3.3)`.

**Comment by groyoh** [comment]
@eliduke `fetch_or_store` is only available in versions `>= 0.3.4` so chances are your project use 0.3.3. Try to update it to use 0.3.4 or 0.3.5.

**Comment by eliduke** [comment]
I ran `bundle update thread_safe` to bring it up to `0.3.5`, and I'm not getting that error anymore. This might be another issue altogether, but, looking at my local server output, the serializer is not being cached. There are still individual db calls for each app_label.

Using version `0.8.3` of AMS and using this caching method:

```
class AppLabelSerializer < ActiveModel::Serializer
  cached
  delegate :cache_key, to: :object

  attributes :id, :key, :label, :label_plural
end
```

There was very clear cache writing and reading in the server output. Is there something else I'm not aware of? Is there some other configuration to get caching up and running with AMS 0.10.0?

**Comment by groyoh** [comment]
@eliduke Might be related to #923. Better to close this issue and open a new one for the cache issue IMO.

@joaomdmoura I think there should be a gem dependency for thread_safe, maybe ">= 3.4"? I know in #833 you guys decided to remove the hardcoded dependency but this issue might pop up again otherwise.

**Comment by eliduke** [comment]
Ok. I will take a look at that other issue, but I will leave this issue open until @joaomdmoura has a chance to take a look at that gem dependancy. Thanks again for your help @groyoh.

**Comment by joaomdmoura** [comment]
Hey ppl! :smile: 
Sorry for take some time to check it, there is a lot going on, I'm working hard on a new freaking awesome feature that will help us into making this Rails 5 integration happen.

So... I've just read the thread, I glad that you guys managed to find the issue, unfortunately as you @groyoh checked at #883 hardcoded dependencies won't play nicely on Rails updates, so I don't believe that's the way to go. 
We have two options, first one would be add a nice reminder at our readme to help new user into make sure they have the right version. The second option would be a fallback, but I'm not sure how the rest of the team would feel about it, id would imply in further  discussions.

I'm aware of #923 and really sad about it :cry: I'll try to personally figure that out! I can't make promises here, as I said, I'm kind busy into this new feature (I'm supposed to open an issue related to it this week), but I'll try to fix it until weekend. Just let me know in case you have some usefull information into debugging it and how you are checking it @eliduke 

I'm not closing it just yet, because at least the reminder at README should be added, let it as open will prevent us to forget about it.

With :heart:

**Comment by groyoh** [comment]
@joaomdmoura what about something like:
```ruby
def self.get_serializer_for(klass)
  serializers_cache.fetch(klass) do
    serializer_class_name = "#{klass.name}Serializer"
    serializer_class = serializer_class_name.safe_constantize
    if serializer_class
      serializers_cache[klass] = serializer_class
    elsif klass.superclass
      serializers_cache[klass] = get_serializer_for(klass.superclass)
    end
  end
end
```
Less beautiful but makes it compatible with any version I think.

**Comment by joaomdmoura** [comment]
@groyoh Indeed, this would make it compatible, but it's definitely not pretty hahaha :smile: 
As we had only one case so far it seems a edge thing, so I'm closing this for now. If this come up again we can work something out.
