### ISSUE TITLE
Slugs as ID's for relationships

### ISSUE THREAD

**Issue by brandonparsons** [rails-api/active_model_serializers#960]
Hi there,

I'm trying to use the JSON API adapter for AMS. Some of my models use slugs as IDs  - how can I get the ID properties of associated records under `relationships` to use the slugs instead of integer IDs?

I've tried to use 
`attribute :slug, key: :id`
and
```ruby
attribute :id

def id
  object.slug
end
```

**Comment by bf4** [comment]
Did either of those work? What happened? Which version/ref or AMS are you on? Which Rails are on you? Which Ruby?

**Comment by bf4** [comment]
Per JSON-API, ids must be immutable and unique. Both integer and uuid are discussed. Are you sure your slugs are immutable and unique?

**Comment by brandonparsons** [comment]
@bf4 Neither of those worked - I ended up getting integer IDs back in both scenarios, which is not the behaviour I had hoped for.

The slugs should be immutable and unique. I'm using `friendly_id`, which checks for uniqueness of slugs.  Slugs are assigned on create, and never changed.

**Comment by bf4** [comment]
Thanks
> What happened? Which version/ref or AMS are you on? Which Rails are on you? Which Ruby?

**Comment by joaomdmoura** [comment]
@bf4 it's 0.10.x because there was no adapter pattern before that.
@brandonparsons indeed the solutions you implemented aren't supposed to work. The JSON API adapter automatically sets the id and and type of the resource being serialized.

*Extracted from [here](https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model/serializer/adapter/json_api.rb#L95)*
```ruby
def resource_object_for(serializer, options)
  options[:fields] = @fieldset && @fieldset.fields_for(serializer)
  options[:required_fields] = [:id, :type]

  cache_check(serializer) do
    attributes = serializer.attributes(options)

    result = {
      id: attributes.delete(:id).to_s,
      type: attributes.delete(:type)
    }

    result[:attributes] = attributes if attributes.any?
    result
  end
end
```

We could add some kind of option, or method on the serializer that would enable you to override the attribute being used as id.
something like:
```ruby
attributes :title, :body
identifier: slug
```
But I'm not sure if it's an edge-case or not. I'll give it some thought.

**Comment by brandonparsons** [comment]
FWIW, it appears that jsonapi-resources has the same behavior.

Don't implement this just for me if I'm the only one asking about it! What
I'm trying to do could be an anti-pattern.

**Comment by beauby** [comment]
Closing this, as we have integrated the ability to override `id` in master. Feel free to reopen if needed.
