### ISSUE TITLE
Is "context" a reserved word?

### ISSUE THREAD

**Issue by wrburgess** [rails-api/active_model_serializers#976]
I have an serializer associated with a model that owns an attribute named `context`. Despite data being present in the `context` field, the serializer always returns a `nil` value for that particular attribute.

Is the word `context` a reserved word for active model serializers or is another issue at hand?

Here's the database record
```
#<ConferenceSession:0x007faddbd721a8
 id: 6,
 user_id: 316,
 conference_id: 166,
 context: "teacher_app",
 created_at: Mon, 29 Jun 2015 16:32:36 UTC +00:00,
 updated_at: Mon, 29 Jun 2015 16:32:36 UTC +00:00,
 client_updated_at: Tue, 30 Jun 2015 16:32:36 UTC +00:00>
```

Here's the JSON response from the serializer:

```
{"conference_session"=>
  {"id"=>6,
   "user_id"=>316,
   "conference_id"=>166,
   "context"=>nil,
   "updated_at"=>"2015-06-29T16:32:36.614Z",
   "created_at"=>"2015-06-29T16:32:36.603Z",
   "client_updated_at"=>"2015-06-30T16:32:36.000Z"}}
```

**Comment by joaomdmoura** [comment]
@wrburgess what version of AMS and Rails are you using? Could you please share your serializer too? :smile:

**Comment by wrburgess** [comment]
## library versions
```
ruby "2.2.0"
gem "rails", "4.2.3"
gem "active_model_serializers", "0.9.3"
```

## Serializer

```
class ConferenceSessionSerializer < ActiveModel::Serializer
  attributes(
    :id,
    :user_id,
    :conference_id,
    :context,
    :updated_at,
    :created_at,
    :client_updated_at
  )
end
```

**Comment by joaomdmoura** [comment]
So yes @wrburgess, in 0.9.x ```context``` is a reserved word.
But I would strongly recommend you to check and use the 0.10.x :smile: we are working pretty hard on it and the RC2 is pretty damn solid.
I'm closing this one for now but let me know if there is something we can help you with :smile:

**Comment by wrburgess** [comment]
Thanks for the reply and answer!

**Comment by toobulkeh** [comment]
sounds like you guys are recommending 0.10.x pretty heavily, and a lot of features are only on that, but the README still says 0.9.x. Any recommendations to standardize the message to us plebeian users? :)

And as a follow on, is `object` still reserved in 0.10.x? It's a core symbol to getstream.io, which is why i ask.

**Comment by wrburgess** [comment]
@joaomdmoura I tried to upgrade to 0.10.x on a branch and a good portion of my specs blew up. Without full documentation to know what/why I need to change, it's hard to spend the time trying to accommodate the changes in the new version.

**Comment by joaomdmoura** [comment]
@toobulkeh and @wrburgess 
Indeed, we have being promoting 0.10.x! :smile:

As soon as we officially release it, we will update the README, but it's already being used in production for some ppl, and pretty stable, so I would recommend anyone to give it a try.

Yeap, we kept ```object``` working the same way it was on older versions.

In order to make it easy to update and use 0.10.x we decided to start building some docs, it will probably include some instructions about how to update it from older versions too @wrburgess. I've just opened the PR with the initial proposal (#944) check it out and +1 if it's something that you agree.
